name: Release Course Packages
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Extract tag name
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Export to SCORM 1.2
      id: export-scorm
      uses: LiaScript/LiaScript-Exporter@master
      with:
        input-file: 'README.md'
        format: 'scorm1.2'
        output-name: 'course-${{ env.TAG_NAME }}-scorm1.2'
        scorm-organization: 'My Organization'
        scorm-mastery-score: '80'
    
    - name: Export to PDF
      id: export-pdf
      uses: LiaScript/LiaScript-Exporter@master
      with:
        input-file: 'README.md'
        format: 'pdf'
        output-name: 'course-${{ env.TAG_NAME }}'
        pdf-format: 'A4'
        pdf-landscape: false
    
    - name: Export to Web
      id: export-web
      uses: LiaScript/LiaScript-Exporter@master
      with:
        input-file: 'README.md'
        format: 'web'
        output-name: 'course-${{ env.TAG_NAME }}-web'
        web-zip: true
        web-indexeddb: true
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.export-scorm.outputs.output-file }}
          ${{ steps.export-pdf.outputs.output-file }}
          ${{ steps.export-web.outputs.output-file }}
        body: |
          Course packages for ${{ env.TAG_NAME }}
          
          - SCORM 1.2 package for LMS deployment
          - PDF version for offline reading
          - Web package for standalone hosting
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}